

input = '''
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............'''

input = open('input7.txt', 'r').read()

rows = input.strip('\n').split('\n')
beams = list(rows[0].replace('S', '|'))

splits = 0
total = 0
for row in rows[1:]:
    for x in range(len(row)):
        if row[x] == '^' and beams[x] == '|':
            total += 1
            if x > 0:
                beams[x-1] = '|'
            if x < len(beams) - 1:
                beams[x+1] = '|'
            beams[x] = '.'
    print(row)
    print(''.join(beams))

print(total)
