

input = '''
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............'''

input = open('input7.txt', 'r').read()

rows = input.strip('\n').split('\n')
beams = list(map(int, rows[0].replace('S', '1').replace('.', '0')))

splits = 0
total = 0
for row in rows[1:]:
    for x in range(len(row)):
        if row[x] == '^' and beams[x] > 0:
            total += 1
            if x > 0:
                beams[x-1] += beams[x]
            if x < len(beams) - 1:
                beams[x+1] += beams[x]
            beams[x] = 0
    print(row)
    print(beams, sum(beams))

print(sum(beams))
